#!/bin/sh
#
# Copyright (C) 2014-2016 OpenMediaVault Plugin Developers
#
# This file is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# This file is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this file. If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

RUN_AS="emby"
RUN_GRP="nogroup"
SERVICE="emby"
SERVICE_XPATH="//services/${SERVICE}"
BIN="/usr/local/bin"
FFMPEG_LINK="/usr/local/bin/ffmpeg"
LINK="https://github.com//MediaBrowser/Emby/releases/latest"
FILE="/tmp/Emby.Mono.zip"
INSTALL_DIR="/opt/${SERVICE}"
LIBS_AMD64="https://github.com/tekkbebe/OMV.Resources/raw/master/libs/embylibsamd64/embylibs.zip"
LIBS_I386="https://github.com/tekkbebe/OMV.Resources/raw/master/libs/embylibsi386/embylibs.zip"
LIBS_ARMHF="https://github.com/tekkbebe/OMV.Resources/raw/master/libs/embylibsarmhf/embylibs.zip"
LIBS_FILE="/tmp/embylibs.zip"
LIBS_DIR="/opt/${SERVICE}/embylibs"
IMAGEMAGICK_CONF="/opt/${SERVICE}/ImageMagickSharp.dll.config"
SQLITE3_CONF="/opt/${SERVICE}/System.Data.SQLite.dll.config"

if [ "$(omv_config_get "${SERVICE_XPATH}/enable")" != "1" ]; then
    update-rc.d ${SERVICE} disable || :
fi

install()
{
    if omv_config_exists "${SERVICE_XPATH}"; then
        data_directory="$(omv_config_get "${SERVICE_XPATH}/db-folder")"
        xmlstarlet ed -L -u "${SERVICE_XPATH}/old_db-folder" -v "" -n ${OMV_CONFIG_FILE}
    fi
    
    if [ "${data_directory}" = "" ]; then
        data_directory="/var/lib/${SERVICE}"
    fi

    if [ ! -d "${data_directory}" ]; then
        mkdir -p "${data_directory}"
        usermod -d "${data_directory}" "${SERVICE}"
        chown ${RUN_AS}:${RUN_GRP} ${data_directory}
    fi

    if [ ! -d "${BIN}" ]; then
        mkdir -p "${BIN}"
    fi

    if [ -d "${INSTALL_DIR}/ProgramData-Server" ]; then
        echo "Moving data directory from <${INSTALL_DIR}/ProgramData-Server> to <${data_directory}>..."
        if [ ! -d "${data_directory}/ProgramData-Server" ]; then
            cp -rf ${INSTALL_DIR}/ProgramData-Server ${data_directory}
            rm -rf "${INSTALL_DIR}"
            chown -R ${RUN_AS}:${RUN_GRP} ${data_directory}
        fi
    fi

    if [ ! -d "${INSTALL_DIR}" ]; then
        mkdir -p "${INSTALL_DIR}"
    fi

    if [ -f "${FILE}" ]; then
        rm -f ${FILE}
    fi
    
    echo "Downloading..."
    curl -s -L ${LINK} | grep 'Emby.Mono.zip' | head -n 1 | sed -r 's/.{21}//' | sed -r 's/.{17}$//' | wget --base=http://github.com/ -i - -O ${FILE}

    echo "Extracting..."
    unzip -o ${FILE} -d ${INSTALL_DIR}
    rm -f ${FILE}

    if [ -f "${LIBS_FILE}" ]; then
        rm -f ${LIBS_FILE}
    fi

    if arch | grep x86_64 >/dev/null 2>&1; then
        LIBS_LINK="${LIBS_AMD64}"
        echo "cpu 64 bit..."
    elif arch | grep 86 >/dev/null 2>&1; then
        LIBS_LINK="${LIBS_I386}"
        echo "cpu 32 bit..."
    elif arch | grep armv7l >/dev/null 2>&1; then
        LIBS_LINK="${LIBS_ARMHF}"
        echo "cpu armhf..."
    else
        echo "cpu architecture not supported.  exiting..."
        exit 0
    fi

    if [ -f "${LIBS_FILE}" ]; then
        rm -f ${FILE}
    fi

    echo "Downloading..."
    wget ${LIBS_LINK} -O ${LIBS_FILE}

    echo "Extracting..."
    unzip -o ${LIBS_FILE} -d ${LIBS_DIR}
    rm -f ${LIBS_FILE}

    echo "Creating imagemagick config..."
    cat <<EOF > "${IMAGEMAGICK_CONF}"
<configuration>
  <dllmap dll="CORE_RL_Wand_.dll" target="libMagickWand-6.Q8.so.2" os="linux"/>
</configuration>  
EOF

    echo "Creating sqlite3 config..."
    cat <<EOF > "${SQLITE3_CONF}"
<configuration>
  <dllmap dll="sqlite3" target="libsqlite3.so" os="linux"/>
</configuration>
EOF

    chown -R ${RUN_AS}:${RUN_GRP} ${INSTALL_DIR}
    chmod 755 ${INSTALL_DIR}/embylibs/*
    chmod 755 ${INSTALL_DIR}/MediaBrowser.Server.Mono.exe
    ldconfig

    echo "Calling insserv..."
    insserv ${SERVICE}
    echo "...ok"
}

case $2 in
    install)
        echo "Installing Emby..."
        install
    ;;

    update)
        echo "Updating Emby..."
        update-rc.d ${SERVICE} stop
        install
    ;;

    moveDbFolder)
        if omv_config_exists "${SERVICE_XPATH}/old_db-folder"; then
            current_data_directory="$(omv_config_get "${SERVICE_XPATH}/old_db-folder")"

            if [ "${current_data_directory}" != "" ]; then
                if [ -d "${current_data_directory}" ]; then
                    data_directory="$(omv_config_get "${SERVICE_XPATH}/db-folder")"
                    echo "Moving database from <${current_data_directory}> to <${data_directory}>..."

                    if [ ! -d "${FFMPEG_LINK}" ]; then
                        cp -rfp ${current_data_directory}/ffmpeg ${FFMPEG_LINK}
                        rm -rf ${current_data_directory}/ffmpeg
                        ln -s ${FFMPEG_LINK} ${current_data_directory}/ffmpeg
                        chmod 755 ${FFMPEG_LINK}/*/ffmpeg
                        chmod 755 ${FFMPEG_LINK}/*/ffprobe
                        chmod 755 ${FFMPEG_LINK}/*/fonts/ARIALUNI.TTF
                    fi
                    
                    if [ ! -d "${data_directory}/cache" ]; then
                        cp -rfp "${current_data_directory}" "${data_directory}"
                        rm -rf "${current_data_directory}"
                        usermod -d "${data_directory}" "${SERVICE}"
                    fi
                    
                    chown -R ${RUN_AS}:${RUN_GRP} "${data_directory}"

                fi
                xmlstarlet ed -L -u "${SERVICE_XPATH}/old_db-folder" -v "" -n ${OMV_CONFIG_FILE}
            fi
        fi
    ;;

    *)
    ;;
esac

if [ "$(omv_config_get "${SERVICE_XPATH}/enable")" != "0" ]; then
    invoke-rc.d ${SERVICE} start
fi

exit 0

