#!/bin/sh

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

case "$1" in
    purge)
        SERVICE_XPATH_NAME="emby"
        SERVICE_XPATH="/config/services/${SERVICE_XPATH_NAME}"
        DATADIR="$(omv_config_get "${SERVICE_XPATH}/db-folder")"
        FFMPEG_LINK="/usr/local/bin/ffmpeg"

        if [ -f "/var/run/${SERVICE_XPATH_NAME}/${SERVICE_XPATH_NAME}.pid" ]; then
            PID=`cat /var/run/${SERVICE_XPATH_NAME}/${SERVICE_XPATH_NAME}.pid`;
            if ! kill -0 $PID > /dev/null 2>&1; then
                echo "Removing stale pid file"
                rm /var/run/${SERVICE_XPATH_NAME}/${SERVICE_XPATH_NAME}.pid
            else
                kill -9 $PID;
            fi
        fi

        if [ -e "${FFMPEG_LINK}" ]; then
            rm -Rf "${FFMPEG_LINK}"
        fi

        if [ -d "/opt/${SERVICE_XPATH_NAME}" ]; then
            rm -rf "/opt/${SERVICE_XPATH_NAME}"
        fi

        if [ -d "/var/run/${SERVICE_XPATH_NAME}" ]; then
            rm -rf "/var/run/${SERVICE_XPATH_NAME}"
        fi

        if [ -d "${DATADIR}" ]; then
            rm -rf "${DATADIR}"
        fi

        if omv_config_exists "${SERVICE_XPATH}"; then
            omv_config_delete "${SERVICE_XPATH}"
        fi
        
        if getent passwd emby >/dev/null 2>&1; then
            userdel emby
        fi
    ;;

    remove)
    ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
